# Generated by Django 6.0.7 on 2026-08-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('profile_pic', models.ImageField(default='', upload_to='userPics')),
            ],
        ),
    ]
