# Generated by Django 6.0.7 on 2026-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_ownerdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerDetail',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
    ]
