# Generated by Django 6.0.7 on 2026-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_delete_ownerdetail_alter_userdetail_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetail',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('blood_group', models.CharField()),
                ('donation_date', models.CharField()),
                ('not_donated', models.CharField()),
                ('profile_pic', models.ImageField(default='', upload_to='donorPics')),
                ('health_conditions', models.CharField()),
            ],
        ),
    ]
