# Generated by Django 6.0.7 on 2026-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_donordetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('patient_name', models.CharField(max_length=45)),
                ('patient_phone', models.CharField(max_length=13)),
                ('patient_email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('required_blood_group', models.CharField(max_length=5)),
                ('locality', models.CharField(default='', max_length=100)),
                ('condition', models.TextField(blank=True, null=True)),
                ('hospital', models.CharField(default='', max_length=100)),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='medicalReports')),
            ],
        ),
        migrations.RemoveField(
            model_name='donordetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donordetail',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='donordetail',
            name='not_donated',
        ),
        migrations.RemoveField(
            model_name='donordetail',
            name='password',
        ),
        migrations.RemoveField(
            model_name='donordetail',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='donordetail',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donordetail',
            name='locality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donordetail',
            name='never_donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donordetail',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='donordetail',
            name='health_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
