# Generated by Django 6.0.7 on 2026-08-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_patientdetail_remove_donordetail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetail',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
