# Generated by Django 6.0.7 on 2026-08-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_donordetail_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDetail',
        ),
    ]
