# Generated by Django 6.0.7 on 2026-08-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_patientdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDetail',
        ),
    ]
