# Generated by Django 6.0.7 on 2026-08-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_delete_patientdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('patient_name', models.CharField(max_length=45)),
                ('patient_phone', models.CharField(max_length=13)),
                ('patient_email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('required_blood_group', models.CharField(max_length=5)),
                ('locality', models.CharField(default='', max_length=100)),
                ('condition', models.TextField(blank=True, null=True)),
                ('hospital', models.CharField(default='', max_length=100)),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='medicalReports')),
            ],
        ),
    ]
