# Generated by Django 6.0.7 on 2026-08-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_delete_donordetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetail',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('locality', models.CharField(default='', max_length=100)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('never_donated', models.BooleanField(default=False)),
                ('health_conditions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
