# Generated by Django 6.1 on 2026-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_donordetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
